name: Azure Web App Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wimacr.azurecr.io/fastapi_todo:${{ github.sha }}
          file: Dockerfile

      - name: Azure Web App deployment
        uses: Azure/webapps-deploy@v2
        with:
          app-name: wimwebapp
          images: wimacr.azurecr.io/fastapi_todo:${{ github.sha }}
          action: "Run"